name: bored_app
description: An app to cure your bordem

publish_to: 'none'
version: 1.0.5

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  swiping_card_deck: ^1.2.0
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.7.0"


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon.png"
  image_path_android: "assets/icon.png"
  adaptive_icon_background: "assets/back.png"
  adaptive_icon_foreground: "assets/fore.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Nanum
      fonts:
        - asset: fonts/Nunito-VariableFont_wght.ttf